import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import localFont from "next/font/local"

const nanumR = localFont({
  src: "./fonts/NanumSquareR.ttf",
  display: "swap",
});
const nanumB = localFont({
  src: "./fonts/NanumSquareB.ttf",
  display: "swap",
});

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '투두리스트',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nanumR.className}>{children}</body>
    </html>
  )
}