import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import localFont from "next/font/local"
import Link from "next/link";
import Image from 'next/image'

const nanumR = localFont({
  src: "./fonts/NanumSquareR.ttf",
  display: "swap",
});
const nanumB = localFont({
  src: "./fonts/NanumSquareB.ttf",
  display: "swap",
});

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '투두리스트',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nanumR.className}>
        <div className="h-[60px] bg-white pl-[250px] flex items-center"> 
          <Link href="/">
            <Image src="/img/logo.svg" alt="로고" width={150} height={40} />
          </Link>
        </div>
        {children}
      </body>
    </html>
  )
}